# Generated by Django 4.2.2 on 2023-06-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('dose', models.DecimalField(decimal_places=2, max_digits=7)),
                ('unitOfMeasurement', models.CharField(max_length=10)),
                ('time', models.CharField(choices=[('QD', 'daily (QD)'), ('BID', 'twice a day (BID)'), ('TID', 'three times a day (TID)'), ('QID', 'four times a day (QID)'), ('PRN', 'as needed (PRN)'), ('QHS', 'at bedtiitme (QHS)')], max_length=3)),
                ('reason', models.CharField(max_length=30)),
                ('notes', models.TextField(blank=True, max_length=250)),
            ],
        ),
    ]
